### PR TITLE
Extra tools/checks in pre-commit

### PR DESCRIPTION
**Pull request by mdeweerd**

### CODE REVIEW

**Comment by CreatingNull** [comment]
Thanks again for your contributions. 
I'd prefer to introduce any new hooks on a individual basis, rather than as a batch.

**Comment by mdeweerd** [comment]
You want me to split this in 10+ PRs?

- It will most certainly result in conflicts to resolve between the PRs.

Options:
- You could merge this and remove what you do not want
- You could tell me what you want to keep and I'll remove the rest
- This PR can be abandoned.

**Comment by CreatingNull** [comment]
Definitely don't split it. I'm leaving it open for now until I have time to review all the hooks you proposed. Thanks again!

**Comment by CreatingNull** [comment]
Closing, as I've accepted the majority of the hooks.

The ones I've excluded (for now):

- no-commit-to-branch - If we got more contributions I may reconsider this.
- all the flake8 stuff - This is just personal linting preference, will eventually migrate things to ruff anyway.

Thanks for the suggestions, definitely some cool tools that I can use on other projects as well.

**Pull request closed without merging**
